generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingfederate-data
  namespace: ping
  files:
    - data.json
  literals:
    - IMPORT_DATA=true

secretGenerator:
- name: pingfederate-jwk
  namespace: ping
  files:
    - pf.jwk